import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import router from './router';
import i18n from './plugins/i18n';
import {
  create,
  NMessageProvider,
  NConfigProvider,
  darkTheme,
  lightTheme,
  NButton,
  NInput,
  NForm,
  NFormItem,
  NCard,
  NSpace,
  NLayout,
  NLayoutHeader,
  NLayoutContent,
  NLayoutFooter,
  NMenu,
  NIcon,
  NDropdown,
  NAvatar,
  NBadge,
  NSwitch,
  NSelect,
  NUpload,
  NProgress,
  NModal,
  NAlert,
  NDivider,
  NList,
  NListItem,
  NThing,
  NTag,
  NSpin,
  NEmpty,
  NPagination,
  NGrid,
  NGridItem,
  NTabs,
  NTabPane,
  NDataTable,
  NPopover,
  NTooltip,
  NCollapse,
  NCollapseItem,
  NTimeline,
  NTimelineItem,
  NResult,
  NStatistic,
  NDrawer,
  NDrawerContent,
  NInputGroup,
  NInputNumber,
  NRadioGroup,
  NRadio,
  NCheckbox,
  NCheckboxGroup,
  NSlider,
  NDatePicker,
  NTimePicker,
  NColorPicker,
  NTransfer,
  NTree,
  NTreeSelect,
  NCascader,
  NRate,
  NMention,
  NBackTop,
  NLoadingBarProvider,
  NDialogProvider,
  NNotificationProvider,
} from 'naive-ui';
import './style.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

const app = createApp(App);
const pinia = createPinia();

// 创建 Naive UI 实例
const naive = create({
  components: [
    NMessageProvider,
    NConfigProvider,
    NButton,
    NInput,
    NForm,
    NFormItem,
    NCard,
    NSpace,
    NLayout,
    NLayoutHeader,
    NLayoutContent,
    NLayoutFooter,
    NMenu,
    NIcon,
    NDropdown,
    NAvatar,
    NBadge,
    NSwitch,
    NSelect,
    NUpload,
    NProgress,
    NModal,
    NAlert,
    NDivider,
    NList,
    NListItem,
    NThing,
    NTag,
    NSpin,
    NEmpty,
    NPagination,
    NGrid,
    NGridItem,
    NTabs,
    NTabPane,
    NDataTable,
    NPopover,
    NTooltip,
    NCollapse,
    NCollapseItem,
    NTimeline,
    NTimelineItem,
    NResult,
    NStatistic,
    NDrawer,
    NDrawerContent,
    NInputGroup,
    NInputNumber,
    NRadioGroup,
    NRadio,
    NCheckbox,
    NCheckboxGroup,
    NSlider,
    NDatePicker,
    NTimePicker,
    NColorPicker,
    NTransfer,
    NTree,
    NTreeSelect,
    NCascader,
    NRate,
    NMention,
    NBackTop,
    NLoadingBarProvider,
    NDialogProvider,
    NNotificationProvider,
  ],
});

app.use(pinia);
app.use(i18n);
app.use(naive);
app.use(router);

app.mount('#app');
